=== gongchuanjing/InterestingJavaSE/src/tk/chuanjing/stage4web/chapter10/xml/demo1.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT persons (person+)>
<!ELEMENT person (n	<element name="person">
		<complexType>
			<sequence>	 
				<!-- 简单标签 -->
				<element name="name" type="string"></element>
				<element name="age" type="int"></element>
				<element name="sex" type="string"></element>
			</sequence>
		</complexType>
	</element>x)*>

<!ELEMENT name (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT sex (#PCDATA)>

<!ATTLIST person id ID #REQUIRED>

=== gongchuanjing/InterestingJavaSE/src/tk/chuanjing/stage4web/chapter10/xml/demo1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE persons SYSTEM "demo1.dtd">
<!-- XML的注释 -->
<persons>
	<person id="aaa">
		<name>李旭华</name>
		<age>38</age>
		<sex>男</sex>
	</person>
	
	<person id="bbb">
		<name>李冠希</name>
		<age>28</age>
		<sex>男</sex>
	</person>
</persons>
